<h1>PRODUCT EDIT</h1>

<b><?=Session::getFlash()?></b>

<form method="post" enctype="multipart/form-data">
    <input type="text" name="title" value="<?=$form->title?>"> <br>
    <input type="text" name="price" value="<?=$form->price?>"> <br>
    <select name="category">
        <?php foreach ($categories as $category): ?>
            <option value="<?= $category['id'] ?>" <?=$category['id'] == $product['category_id'] ? 'selected' : '' ?> >
                <?=$category['name']?>
            </option>
        <?php endforeach; ?>
    </select>

    <textarea name="description"><?=$form->description?></textarea>

    <input type="hidden" value="1" name="status">

<!--    <input type="file" name="document">-->
    
    <button>Go</button>
</form>