<h1>PRODUCTS</h1>

<b><?=Session::getFlash()?></b>

<table width="100%" border="1">
    <tr>
        <td>ID</td>
        <td>Title</td>
        <td>Price</td>
        <td>Actions</td>
    </tr>

    <?php foreach ($products as $product ): ?>
        <tr>
            <td><?=$product['id']?></td>
            <td><?=$product['title']?></td>
            <td><?=$product['price']?></td>
            <td>
                <a href="#">Edit</a>
                <a href="/admin/products/remove-<?=$product['id']?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>

</table>