<h1>CONTACT</h1>

<div>Asperiores, itaque vero facere laudantium voluptas temporibus mollitia nisi deleniti illo minima quisquam corporis possimus nesciunt.</div>
<br>


<b><?=Session::getFlash()?></b>
<form method="post">
    <input type="text" name="username" placeholder="Username" value="<?=$form->username?>"><br>
    <input type="email" name="email" placeholder="Email" value="<?=$form->email?>"><br>
    <textarea name="message" placeholder="Message"><?=$form->message?></textarea>
    <button>SEND MESSAGE</button>
</form>