<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My project</title>
</head>
<body>
<a href="/">Home</a>
<a href="#">Services</a>
<a href="/products">Products</a>
<a href="/contact-us">Contact</a>
|
<?php if (!Session::has('user')) : ?>
    <a href="/login">Login</a>
<?php else : ?>
    <a href="/logout">Logout</a>
<?php endif ?>
<hr>
<?=$content ?>
<br>
<br>
<br>
<br>
<br>
<hr>
Copyright &copy; 2016 Company Name
</body>
</html>